### ISSUE TITLE
VSCode + TensorBoard: TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by tchaton** [pytorch/kineto#299]
Dear people from Kineto Team,

I have generated traces using PyTorch Lightning Kineto Integration, moved them to another machine using scp and tried to open them inside a my local VSCode + TensorBoard and got this error. 

```
E0616 18:42:06.406091 123145476980736 _internal.py:225] Error on request:
Traceback (most recent call last):
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/tensorboard/backend/application.py", line 526, in __call__
    return self._app(environ, start_response)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/tensorboard/backend/application.py", line 567, in wrapper
    return wsgi_app(environ, start_response)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/tensorboard/backend/security_validator.py", line 80, in __call__
    return self._application(environ, start_response_proxy)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/tensorboard/backend/path_prefix.py", line 71, in __call__
    return self._application(environ, start_response)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/tensorboard/backend/experiment_id.py", line 76, in __call__
    return self._application(environ, start_response)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/tensorboard/backend/empty_path_redirect.py", line 47, in __call__
    return self._application(environ, start_response)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/tensorboard/backend/application.py", line 590, in wrapper
    return wsgi_app(environ, start_response)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/tensorboard/backend/application.py", line 549, in _route_request
    return self.exact_routes[clean_path](environ, start_response)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/werkzeug/wrappers/request.py", line 206, in application
    resp = f(*args[:-2] + (request,))
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/torch_tb_profiler/plugin.py", line 153, in overview_route
    gpu_metrics_data, gpu_metrics_tooltip = profile.get_gpu_metrics_data_tooltip()
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/torch_tb_profiler/run.py", line 217, in get_gpu_metrics_data_tooltip
    data, has_occupancy, has_sm_efficiency = get_gpu_metrics_data(self)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/torch_tb_profiler/run.py", line 199, in get_gpu_metrics_data
    round(profile.sm_efficency[gpu_id] * 100, 2))})
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Comment by gaoteng-git** [comment]
> Dear people from Kineto Team,
> 
> I have generated traces using PyTorch Lightning Kineto Integration, moved them to another machine using scp and tried to open them inside a my local VSCode + TensorBoard and got this error.
> 
> ```
> E0616 18:42:06.406091 123145476980736 _internal.py:225] Error on request:
> Traceback (most recent call last):
>   File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 319, in run_wsgi
>     execute(self.server.app)
>   File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 308, in execute
>     application_iter = app(environ, start_response)
>   File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/tensorboard/backend/application.py", line 526, in __call__
>     return self._app(environ, start_response)
>   File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/tensorboard/backend/application.py", line 567, in wrapper
>     return wsgi_app(environ, start_response)
>   File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/tensorboard/backend/security_validator.py", line 80, in __call__
>     return self._application(environ, start_response_proxy)
>   File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/tensorboard/backend/path_prefix.py", line 71, in __call__
>     return self._application(environ, start_response)
>   File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/tensorboard/backend/experiment_id.py", line 76, in __call__
>     return self._application(environ, start_response)
>   File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/tensorboard/backend/empty_path_redirect.py", line 47, in __call__
>     return self._application(environ, start_response)
>   File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/tensorboard/backend/application.py", line 590, in wrapper
>     return wsgi_app(environ, start_response)
>   File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/tensorboard/backend/application.py", line 549, in _route_request
>     return self.exact_routes[clean_path](environ, start_response)
>   File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/werkzeug/wrappers/request.py", line 206, in application
>     resp = f(*args[:-2] + (request,))
>   File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/torch_tb_profiler/plugin.py", line 153, in overview_route
>     gpu_metrics_data, gpu_metrics_tooltip = profile.get_gpu_metrics_data_tooltip()
>   File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/torch_tb_profiler/run.py", line 217, in get_gpu_metrics_data_tooltip
>     data, has_occupancy, has_sm_efficiency = get_gpu_metrics_data(self)
>   File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.6/site-packages/torch_tb_profiler/run.py", line 199, in get_gpu_metrics_data
>     round(profile.sm_efficency[gpu_id] * 100, 2))})
> TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
> ```

For re-creating the bug, would you mind sending your traces json file to me? My email: tegao@microsoft.com

**Comment by gaoteng-git** [comment]
@tchaton Fixed in this PR: [](https://github.com/pytorch/kineto/pull/305)
You can install from source code of [plugin/0.2](https://github.com/pytorch/kineto/tree/plugin/0.2) branch, and try it again. We'll pack up latest updates together and update pypi later on. Thanks!
