### ISSUE TITLE
pytorch tutorial results in failing torch_tb_profiler

### ISSUE THREAD

**Issue by stas00** [pytorch/kineto#300]
I tried to replicate: https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html 

when the log is generated and I try to load it, I get:

```
tensorboard --logdir=./log                           
2021-06-16 19:25:39.748760: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784

I0616 19:25:40.729878 139909655127808 plugin.py:292] Monitor runs begin
I0616 19:25:40.731639 139909655127808 plugin.py:310] Find run directory /mnt/nvme1/code/huggingface/torch-profiler/log/resnet18
I0616 19:25:40.732423 139911335974656 plugin.py:358] Load run resnet18
I0616 19:25:40.737549 139911335974656 loader.py:56] starting all processing
Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.5.0 at http://localhost:6006/ (Press CTRL+C to quit)
I0616 19:25:41.582570 139911335974656 plugin.py:362] Run resnet18 loaded
I0616 19:25:41.582768 139911478585088 plugin.py:327] Add run resnet18
W0616 19:25:49.419933 139909848078080 security_validator.py:46] In 3.0, this warning will become an error:
Requires default-src for Content-Security-Policy
E0616 19:25:49.833019 139909848078080 _internal.py:113] Error on request:
Traceback (most recent call last):
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tensorboard/backend/application.py", line 525, in __call__
    return self._app(environ, start_response)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tensorboard/backend/application.py", line 566, in wrapper
    return wsgi_app(environ, start_response)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tensorboard/backend/security_validator.py", line 77, in __call__
    return self._application(environ, start_response_proxy)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py", line 68, in __call__
    return self._application(environ, start_response)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py", line 73, in __call__
    return self._application(environ, start_response)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py", line 43, in __call__
    return self._application(environ, start_response)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tensorboard/backend/application.py", line 589, in wrapper
    return wsgi_app(environ, start_response)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/tensorboard/backend/application.py", line 548, in _route_request
    return self.exact_routes[clean_path](environ, start_response)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/werkzeug/wrappers/base_request.py", line 238, in application
    resp = f(*args[:-2] + (request,))
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch_tb_profiler/plugin.py", line 153, in overview_route
    gpu_metrics_data, gpu_metrics_tooltip = profile.get_gpu_metrics_data_tooltip()
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch_tb_profiler/run.py", line 217, in get_gpu_metrics_data_tooltip
    data, has_occupancy, has_sm_efficiency = get_gpu_metrics_data(self)
  File "/mnt/nvme1/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch_tb_profiler/run.py", line 199, in get_gpu_metrics_data
    round(profile.sm_efficency[gpu_id] * 100, 2))})
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

I tried with the released version and the master torch_tb_profiler with the same results.

```
PyTorch version: 1.9.0+cu111
CUDA used to build PyTorch: 11.1
tensorboard 2.5.0
Python 3.8.8
```

I also tried to downgrade `tensorboard` but the error is the same.

The provided samples work w/o problems:
```
tensorboard --logdir=./samples
```

So basically the problem is then lies in `torch.profiler.tensorboard_trace_handler` not generating some data.

Thank you!

**Comment by stas00** [comment]
Since the provided samples worked correctly, most likely this is a bug in pytorch - filed an issue there https://github.com/pytorch/pytorch/issues/60145

**Comment by stas00** [comment]
```
round(profile.sm_efficency[gpu_id] * 100, 2))})
```
should this be written "efficiency"? as compared to `efficency`

**Comment by gaoteng-git** [comment]
> ```
> round(profile.sm_efficency[gpu_id] * 100, 2))})
> ```
> 
> should this be written "efficiency"? as compared to `efficency`

Thank you! Fixed: https://github.com/pytorch/kineto/pull/307

**Comment by stas00** [comment]
I confirm that https://github.com/pytorch/kineto/pull/305 fixed it - thank you for the quick fix, @gaoteng-git!
