### ISSUE TITLE
Cannot enable torch-tb-profiler under Windows

### ISSUE THREAD

**Issue by cowwoc** [pytorch/kineto#415]
Version 0.2.1

When running tensorboard with this plugin under Windows I get this error on startup:

```
ERROR:tensorboard:Failed to load plugin BasicLoader.load; ignoring it.
Traceback (most recent call last):
  File "C:\Users\Gili\Documents\myproject\python\lib\site-packages\tensorboard\backend\application.py", line 123, in TensorBoardWSGIApp
    plugin = loader.load(context)
  File "C:\Users\Gili\Documents\myproject\python\lib\site-packages\tensorboard\plugins\base_plugin.py", line 362, in load
    return self.plugin_class(context)
  File "C:\Users\Gili\Documents\myproject\python\lib\site-packages\torch_tb_profiler\plugin.py", line 58, in __init__
    self._cache = io.Cache()
  File "C:\Users\Gili\Documents\myproject\python\lib\site-packages\torch_tb_profiler\io\cache.py", line 15, in __init__
    self._manager = mp.Manager()
  File "C:\Python39\lib\multiprocessing\context.py", line 57, in Manager
    m.start()
  File "C:\Python39\lib\multiprocessing\managers.py", line 554, in start
    self._process.start()
  File "C:\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Python39\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Python39\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Python39\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

And the plugin tab does not show up in tensorboard.

**Comment by guyang3532** [comment]
How do you launch the plugin? What is your tensorboard version?

**Comment by cowwoc** [comment]
@guyang3532 Tensorboard 2.6.0 launched as follows:

```
import time

from tensorboard import program

tb = program.TensorBoard()
tb.configure(argv=[None, '--logdir', "lightning_logs"])
url = tb.launch()
print("Tensorflow listening on ", url)

while True:
    time.sleep(1000)
```

**Comment by cowwoc** [comment]
Oops, I just realized that my launcher was missing the guard block. Here is the updated code:

```
import time

from tensorboard import program

if __name__ == "__main__":
    tb = program.TensorBoard()
    tb.configure(argv=[None, '--logdir', "lightning_logs"])
    url = tb.launch()
    print("Tensorflow listening on ", url)

    while True:
        time.sleep(1000)
```

I no longer get the aforementioned error.
