### ISSUE TITLE
torch_tb_profiler memory_parser throws an error

### ISSUE THREAD

**Issue by jyyon** [pytorch/kineto#504]
When running model training with deepspeed and pytorch profiler, the training runs without exception, but when I try to analyze the profiling result with tensorboard, it throws `assert prev_ts < r.ts` error from memory parser. I didn't use deepspeed model parallel flag and ran it on single machine with 4 GPUs.

deepspeed version = 0.5.9
torch version = 1.10.1
torch_tb_profiler version = 0.3.1

Training code:
```
def train_shard(model, dataset_provider, profile):
    ...
    dataset_iterator, total_length = dataset_provider.get_shard()
    for batch_num, batch in enumerate(tqdm(dataset_iterator)):
        ...
        # Wherever model.step is called, call profiler.step. The model is deepspeed initialized.
        model.step()
        profiler.step()

def main():
    ...
    with torch.profiler.profile(
            activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA],
            schedule=torch.profiler.schedule(
                skip_first=2,
                wait=1,
                warmup=1,
                active=3,
                repeat=2
            ),
            on_trace_ready=tensorboard_trace_handler('path/log/fine_tune_logs'),
            profile_memory=True,
            with_stack=True,
            with_flops=True,
    ) as prof:
        while True:
            complete = train_shard(model, dataset_provider, prof)
            if complete:
                break
```

Error thrown when I ran tensorboard:
```
W0112 16:20:05.917469 4567412160 loader.py:100] Failed to parse profile data for Run fine_tune_logs on ip-x-x-x-x.ec2.internal. Exception=
Traceback (most recent call last):
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/torch_tb_profiler/profiler/loader.py", line 86, in _process_data
    data, trace_path = RunProfileData.parse(worker, span, local_file)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/torch_tb_profiler/profiler/data.py", line 77, in parse
    profile = RunProfileData.from_json(worker, span, trace_json)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/torch_tb_profiler/profiler/data.py", line 97, in from_json
    profile.process()
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/torch_tb_profiler/profiler/data.py", line 217, in process
    self.memory_parser = MemoryParser(self.tid2tree, memory_events)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/torch_tb_profiler/profiler/memory_parser.py", line 76, in __init__
    self.all_records = self.get_preprocessed_records()
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/torch_tb_profiler/profiler/memory_parser.py", line 278, in get_preprocessed_records
    assert prev_ts < r.ts
AssertionError
```

**Comment by aaronenyeshi** [comment]
@robieta @chaekit - could this issue be caused by recent PyTorch Profiler refactors?

**Comment by robieta** [comment]
Possibly. I don't think profiler promises any sort of ordering of events, though they tend to be sorted and that seems to have been baked into the plugin. We should sync with the TB plugin folks and decide what invariants the profiler should actually promise.

**Comment by guotuofeng** [comment]
@cloudhan, would you please take a look?

**Comment by guotuofeng** [comment]
@jyyon, would you please share us your chrome tracing file so that we can take a look?

**Comment by cloudhan** [comment]
The order is enforce on profile json file loading. So I can only imagine the case where 2 events have exactly the same timestamp...

**Comment by guyang3532** [comment]
@jyyon , I can't reproduce this problem. Can you share a complete example code for me to reproduce ? Or share me the chrome tracing file?

**Comment by jyyon** [comment]
After the fix, I am experiencing the following error:
```
Traceback (most recent call last):
  File “/Users/user/Library/Python/3.8/lib/python/site-packages/torch_tb_profiler/profiler/loader.py”, line 88, in _process_data
    data = RunProfileData.parse(worker, span, local_file, self.caches.cache_dir)
  File “/Users/user/Library/Python/3.8/lib/python/site-packages/torch_tb_profiler/profiler/data.py”, line 103, in parse
    profile = RunProfileData.from_json(worker, span, trace_json)
  File “/Users/user/Library/Python/3.8/lib/python/site-packages/torch_tb_profiler/profiler/data.py”, line 111, in from_json
    profile.process()
  File “/Users/user/Library/Python/3.8/lib/python/site-packages/torch_tb_profiler/profiler/data.py”, line 226, in process
    self.memory_snapshot = memory_parser.find_memory_nodes(self.tid2tree)
  File “/Users/user/Library/Python/3.8/lib/python/site-packages/torch_tb_profiler/profiler/memory_parser.py”, line 301, in find_memory_nodes
    all_records = self.get_preprocessed_records()
  File “/Users/user/Library/Python/3.8/lib/python/site-packages/torch_tb_profiler/profiler/memory_parser.py”, line 336, in get_preprocessed_records
    assert addr not in free
```
This seems a different case than above. When I printed `prev_t` and `r.ts`, they were different. In which case can it happen?

**Comment by guotuofeng** [comment]
@jyyon, would you mind share your tracing file to myguo@microsoft.com so that we can take a look?

**Comment by cloudhan** [comment]
The assertion failure of `addr not in free` indicate a double free of same memory address. Since you are not experiencing segfault, then I am suspecting that there might be some allocations are not correctly recorded. If you @jyyon  could provide a step-by-step reproduce, then it will be of great help.

**Comment by jyyon** [comment]
@guotuofeng sent email to share tracing file.
@cloudhan In this case, metrics collection is more likely an issue? I don't have shareable reproducible code yet.

**Comment by guotuofeng** [comment]
@jyyon, thank for your shared data. The issue should be fixed in PR https://github.com/pytorch/kineto/pull/559
