### ISSUE TITLE
TypeError: bad operand type for unary -: 'NoneType'

### ISSUE THREAD

**Issue by hnt2601** [pytorch/kineto#897]
I get an error when trying to parse_json trace for this profile data
[Uploading resnet18.1712071266259886468.pt.trace.json…]()

Traceback (most recent call last):
  File "debug.py", line 17, in <module>
    profile = parse_json_trace(trace_log)
  File "debug.py", line 10, in parse_json_trace
    return RunProfileData.from_json(worker_name, 0, trace_json)
  File "/home/hoangnt/DL-verification/third-party/kineto/tb_plugin/torch_tb_profiler/profiler/data.py", line 113, in from_json
    profile.process()
  File "/home/hoangnt/DL-verification/third-party/kineto/tb_plugin/torch_tb_profiler/profiler/data.py", line 174, in process
    self.tid2tree, self.pl_tid2tree = parser.parse(self.events, self.forward_backward_events)
  File "/home/hoangnt/DL-verification/third-party/kineto/tb_plugin/torch_tb_profiler/profiler/event_parser.py", line 424, in parse
    tid2tree = builder.build_tree(tid2list, tid2zero_rt_list, staled_device_nodes, fwd_bwd_map=fwd_bwd_map)
  File "/home/hoangnt/DL-verification/third-party/kineto/tb_plugin/torch_tb_profiler/profiler/op_tree.py", line 52, in build_tree
    OpTreeBuilder._build_backward_module(module, None, fwd_bwd_root, backward_modules)
  File "/home/hoangnt/DL-verification/third-party/kineto/tb_plugin/torch_tb_profiler/profiler/op_tree.py", line 290, in _build_backward_module
    OpTreeBuilder._build_backward_module(child, parent, fwd_bwd_map, result)
  File "/home/hoangnt/DL-verification/third-party/kineto/tb_plugin/torch_tb_profiler/profiler/op_tree.py", line 294, in _build_backward_module
    parent.fill_stats()
  File "/home/hoangnt/DL-verification/third-party/kineto/tb_plugin/torch_tb_profiler/profiler/node.py", line 400, in fill_stats
    self.children.sort(key=lambda x: (x.start_time, -x.end_time))
  File "/home/hoangnt/DL-verification/third-party/kineto/tb_plugin/torch_tb_profiler/profiler/node.py", line 400, in <lambda>
    self.children.sort(key=lambda x: (x.start_time, -x.end_time))
TypeError: bad operand type for unary -: 'NoneType'

**Comment by wizzniu** [comment]
@hnt2601 Can you post your json file here? ( The json file from the link is unavailable now

**Comment by hnt2601** [comment]
@wizzniu this is my error file
https://drive.google.com/file/d/1iZDWIET1s6iLwaRB1xD-lm4556hjazZE/view?usp=sharing

**Comment by hnt2601** [comment]
I saw this commit fixed that issue. Thanks
https://github.com/pytorch/kineto/commit/9bc5b9987d2e95fa9caa752a70c3c75d1000fc69

**Comment by hnt2601** [comment]
@wizzniu When I check in that code I saw error result for parent-child for PyTorch Module
https://github.com/pytorch/kineto/blob/8acab098b81301cd58f5dc6d21e45798ae3a0233/tb_plugin/torch_tb_profiler/profiler/op_tree.py#L348

```
**current_node aten::upsample_nearest2d, module nn.Module: DetectionModel_0.backward**
current_node ProfilerStep#0, module nn.Module: BCEWithLogitsLoss_1.backward
current_node ProfilerStep#0, module nn.Module: BCEWithLogitsLoss_0.backward
current_node ProfilerStep#0, module nn.Module: BCEWithLogitsLoss_1.backward
current_node ProfilerStep#0, module nn.Module: BCEWithLogitsLoss_0.backward
current_node ProfilerStep#0, module nn.Module: BCEWithLogitsLoss_1.backward
current_node ProfilerStep#0, module nn.Module: BCEWithLogitsLoss_0.backward
```
