### ISSUE TITLE
Upgrade to CUDA 12.4 is causing segfaults in 4 Range Profiler Tests

### ISSUE THREAD

**Issue by sraikund16** [pytorch/kineto#949]
After upgrading the CUDA image to 12.4 we are having segfault failures in the following tests:
	 19 - CuptiRangeProfilerApiTest.asyncLaunchUserRange (SEGFAULT)
	 20 - CuptiRangeProfilerApiTest.asyncLaunchAutoRange (SEGFAULT)
	 24 - CuptiRangeProfilerTest.UserRangeTest (SEGFAULT)
	 25 - CuptiRangeProfilerTest.AutoRangeTest (SEGFAULT)
	 
This is what the backtrace looks like:
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff730f047 in ?? () from /usr/local/cuda-12.2/lib64/libcupti.so.12
(gdb) bt
#0  0x00007ffff730f047 in ?? () from /usr/local/cuda-12.2/lib64/libcupti.so.12
#1  0x00007ffff72f728a in cuptiFinalize () from /usr/local/cuda-12.2/lib64/libcupti.so.12
#2  0x0000000000448a6e in libkineto::CuptiRBProfilerSession::deInitCupti()::{lambda()#1}::operator()() const [clone .isra.0] ()
#3  0x0000000000448cf9 in libkineto::CuptiRBProfilerSession::~CuptiRBProfilerSession() ()
#4  0x000000000041fd20 in libkineto::MockCuptiRBProfilerSession::~MockCuptiRBProfilerSession() ()
#5  0x000000000041d9a7 in CuptiRangeProfilerTest_UserRangeTest_Test::TestBody() ()
#6  0x00000000004cac2d in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#7  0x00000000004bd21e in testing::Test::Run() [clone .part.0] ()
#8  0x00000000004bd935 in testing::TestInfo::Run() [clone .part.0] ()
#9  0x00000000004be395 in testing::TestSuite::Run() [clone .part.0] ()
#10 0x00000000004bfb27 in testing::internal::UnitTestImpl::RunAllTests() ()
#11 0x00000000004bddfb in testing::UnitTest::Run() ()
#12 0x00000000004169a4 in main ()
(gdb) 

cc @briancoutinho

**Comment by nadavrot** [comment]
I can reproduce this issue with 12.4 and 12.8.

**Comment by sraikund16** [comment]
Yeah unfortunately, CUPTI changed all the APIs for this so it needs to be completely rewritten. We have tasks to do so and will try to raise priority on this issue

**Comment by briancoutinho** [comment]
Ack was on leave so just taking a look this week :)

**Comment by sraikund16** [comment]
Sorry the issue with nvperf issue that I was referring to got added in 12.6 which is not related to this:
https://github.com/pytorch/kineto/pull/1015/files#diff-25fc6d111bef93048d8c48bfb68beb5c361efd05b783a39165c8818a607b4015L26
